import fs from 'fs';
import random from 'lodash/number/random';

// names generated by chance.js
const users = [
  { avatar: "homer", name: "Homer Simpson" },
  { avatar: "owl", name: "solittletime" },
  { avatar: "homer", name: "Homer Simpson" }
];

const quotes = [
  'Doh!',
  'Homer, what are you doing on Swittr? Here, have a donut',
  'Thanks Mr Owl. Mmmm... donut'
];

export function generateMessage(x) {
  const message = {};
  const user = users[x];

  message.id = Number(String(random(1, 10000)) + Date.now()).toString(36);
  message.avatar = '/avatars/' + user.avatar;
  message.name = user.name;
  message.time = new Date().toISOString();
  message.body = quotes[x];

  return message;
}